version: "2"
services:
  chrome:
    image: selenium/node-chrome:3.3
    shm_size: 500m
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - local-network

  firefox:
    image: selenium/node-firefox:2.53.1
    shm_size: 500m
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - local-network

  hub:
    image: selenium/hub:3.6.0
    environment:
      GRID_MAX_SESSION: 15
      GRID_TIMEOUT: 60
      GRID_BROWSER_TIMEOUT: 120
    ports:
      - "4444:4444"
    networks:
      - local-network

  test-service:
    image: soda/test-service:0.2.0
    ports:
      - "8080:8080"
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444  
      - AUTH_USER=""
      - AUTH_PASSWORD=""
      - HUB_CLIENT_TIMEOUT=300
    networks:
      - local-network

networks:
  local-network:
